name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      # - name: Run lint
      #   run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build the project
        run: yarn build
