name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    environment: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/paeezan-assignment:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/paeezan-assignment:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/paeezan-assignment:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/paeezan-assignment:buildcache,mode=max
